name: mandarin_indo_app
description: Aplikasi Belajar Bahasa Mandarin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  intl: ^0.18.0
  google_fonts: ^3.0.1
  flutter_sticky_widgets: ^0.0.3
  equatable: ^2.0.5
  url_launcher: ^6.1.8
  pull_to_refresh_flutter3: ^2.0.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/data/kosakata.json
    - assets/data/words.json
# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/logogit.png"

